# Generated by Django 2.2.6 on 2019-10-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OEApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='f_location',
            new_name='file',
        ),
    ]
