# Generated by Django 2.2.6 on 2019-10-30 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OEApp', '0002_auto_20191031_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='name',
        ),
    ]
