# Generated by Django 2.2.6 on 2019-10-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OEApp', '0003_auto_20191031_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='path',
        ),
    ]
