# Generated by Django 2.2.6 on 2019-10-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OEApp', '0004_auto_20191031_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to=''),
        ),
    ]
